### ISSUE TITLE
CI configuration

### ISSUE THREAD

**Issue by mati2251** [collaborative-system/tea#2]
Jobs for building and testing

**Comment by mati2251** [comment]
Jobs: 
* build
* unit tests
* clang-format tests
* memory leak job

**Comment by jagtym** [comment]
I've opened https://github.com/collaborative-system/tea/pull/54 with build job. We can merge that and I'll follow with rest of the jobs in on separate branches.s

**Comment by mati2251** [comment]
Shouldn't it be open? @jagtym

**Comment by jagtym** [comment]
It definitely should. I've must have closed it by accident by linking pull-request that got closed with merge.
